version: "3.7"
services:
  postgres:
    image: custom-postgres:latest
    container_name: postgres 
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_INITIAL_DATABASES}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${CUSTOM_SCRIPTS_FOLDER}/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - postgresdata:/var/lib/postgresql/data/
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  shared-network:
    external: true
    name: ${HOMEPOSE_DOCKER_NETWORK}
volumes:
  postgresdata:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${POSTGRES_MOUNT_POINT}