TIMEOUT_INTERVAL = 2
SLEEP_INTERVAL = 120
CONFIG_FILE_PATH = 'config.ini'

DEFAULT_CONFIG_FILE_PATH = 'config.ini'
DEFAULT_DATABASE_BACKEND = 'postgres'

DEFAULT_WWW_DATA_USER = 'www_data'
DEFAULT_WWW_DATA_USERID = 33
DEFAULT_WWW_DATA_GROUPID = 33

HOSTS_TARGET_FILE_PATH = '/etc/hosts'
DNSMASQ_CONF_TARGET_FILE_PATH = '/etc/dnsmasq.conf'
