version: "3.7"
services:
  nextcloud:
    image: custom-nextcloud:latest
    container_name: nextcloud
    restart: always 
    environment:
      - VIRTUAL_HOST=nextcloud.${HOMEPOSE_HOSTNAME}.${HOMEPOSE_DOMAIN}
      - LETSENCRYPT_HOST=nextcloud.${HOMEPOSE_HOSTNAME}.${HOMEPOSE_DOMAIN}
      - VIRTUAL_PORT=80
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${HOMECLOUD_DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_DATA_DIR=${NEXTCLOUD_DATA_PATH}
      - NEXTCLOUD_ADMIN_USER=${HOMECLOUD_ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${HOMECLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOMEPOSE_IP_ADDRESS} nextcloud.${HOMEPOSE_HOSTNAME}.${HOMEPOSE_DOMAIN}
    volumes:
      - ${NEXTCLOUD_DATA_MOUNT_POINT}:${NEXTCLOUD_DATA_PATH}
      - ${NEXTCLOUD_MOUNT_POINT}:/var/www/html
    ports:
      - ${NEXTCLOUD_PORT}:80
    networks:
      - shared-network
networks:
  shared-network:
    external: true
    name: ${HOMEPOSE_DOCKER_NETWORK}
