name: Code linting 
on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: pip install .
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "homepose"
        use-pylint: true
        use-pycodestyle: false
        use-flake8: true
        use-black: false
        use-mypy: true
        use-isort: false
        extra-pylint-options: "--disable=C0301,C0114"
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
